default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: test_rails_development
  username: carry
  hostname: localhost
  password: "04122002"
  port: "5432"

test:
  <<: *default
  database: test_rails_test

production:
  <<: *default
  database: test_rails_production
  username: test_rails
  password: <%= ENV["TEST_RAILS_DATABASE_PASSWORD"] %>
